# Generated by Django 5.1.6 on 2025-02-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('createde_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('fineshed_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
