# Generated by Django 5.1.6 on 2025-02-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0002_rename_createde_at_to_do_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="to_do",
            name="observacoes",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
