# Generated by Django 5.1.6 on 2025-02-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0003_to_do_observacoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="to_do",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="to_do",
            name="fineshed_at",
            field=models.DateField(null=True),
        ),
    ]
