# Generated by Django 5.1.4 on 2025-02-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0004_alter_to_do_deadline_alter_to_do_fineshed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="to_do",
            name="fineshed_at",
        ),
        migrations.AddField(
            model_name="to_do",
            name="finished_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="to_do",
            name="deadline",
            field=models.DateField(verbose_name="Data Final"),
        ),
        migrations.AlterField(
            model_name="to_do",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
    ]
