# Generated by Django 5.1.6 on 2025-02-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0005_remove_to_do_fineshed_at_to_do_finished_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArquivoDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_arquivo",
                    models.CharField(max_length=255, verbose_name="nome_do_arquivo"),
                ),
                ("tipo", models.CharField(max_length=50, verbose_name="tipo")),
                ("tamanho", models.CharField(max_length=20, verbose_name="tamanho")),
                (
                    "arquivo",
                    models.FileField(upload_to="downloads/", verbose_name="arquivo"),
                ),
            ],
            options={
                "verbose_name": "Arquivo de Download",
                "verbose_name_plural": "Arquivos de Download",
            },
        ),
    ]
